api/urls.py
from django.urls import path
from django.conf.urls import include

from rest_framework import routers, permissions

from api.views import MCUserViewSet

app_name = 'api'

routerUser = routers.SimpleRouter()

routerUser.register('mcuser', MCUserViewSet, basename='mcuser')

urlpatterns = [
    path('user/', include(routerUser.urls)),
]

consultation/urls.py
from django.urls import path

from consultation.views import pick, start, save_additional_personal_data, save_exam,\
    save_period

app_name = 'consultation'

urlpatterns = [
    path('pick', pick, name='pick'),
    path('start/<int:pk_mcuser_as_user>', start, name='start'),
    path('save_additional_personal_data/<int:pk_mcuser>',
         save_additional_personal_data,
         name='save_additional_personal_data'),
    path('save_exam', save_exam, name='save_exam'),
    path('save_period', save_period, name='save_period'),
]

consultation/models.py
from django.db import models

# Create your models here.

consultation/forms.py
from django import forms
from django.core.exceptions import ValidationError

from mc_data.models import AdditionalPersonalData, ValuedMotivation, \
    ValuedContraindication, Spermogram, BiologicalExam, ClinicalExam


class AdditionalPersonalDataForm(forms.ModelForm):

    class Meta:
        model = AdditionalPersonalData
        exclude = ('comment', 'mc_user', 'motivations', \
                   'contraindications', \
                   'registered_by', 'registered_at')


class ValuedMotivationForm(forms.ModelForm):

    class Meta:
        model = ValuedMotivation
        fields = '__all__'


class ValuedContraindicationForm(forms.ModelForm):

    class Meta:
        model = ValuedContraindication
        fields = '__all__'


class ValuedSomethingFormSet(forms.BaseFormSet):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.instances_to_del = []
        self.instances_to_add = []

    def clean(self):
        if any(self.errors):
            # Don't bother validating the formset unless each form is valid on its own
            return

        titles = []

        for form in self.forms:
            if self.can_delete and self._should_delete_form(form):
                continue
            title = form.cleaned_data.get(self.Meta.att_name)
            if title in titles:
                raise ValidationError(f'One value per {something} '
                                      f'(here: at least 2 values for "{title}").')
            if title is not None:
                titles.append(title)


    def save(self, m2mfield):
        thing_to_del = []
        thing_to_add = []
        for form in self.forms:
            if form.cleaned_data.get('value') is not None:
                get_dict = form.cleaned_data.copy()
                to_del = get_dict.pop('DELETE')

                thing_to_del.append(self.Meta.model.objects.filter(
                    **{self.Meta.att_name: form.cleaned_data[self.Meta.att_name]}
                ))

                if not to_del:
                    thing_to_add.append(self.Meta.model.objects.get(**get_dict))


        for query in thing_to_del:
            for m in query:
                m2mfield.remove(m)
        for m in thing_to_add:
            m2mfield.add(m)
            


class ValuedMotivationFormSet(ValuedSomethingFormSet):

    class Meta:
        model = ValuedMotivation
        att_name = 'motivation'
        

class ValuedContraindicationFormSet(ValuedSomethingFormSet):

    class Meta:
        model = ValuedContraindication
        att_name = 'contraindication'

consultation/views.py
from rest_framework import status

from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.forms import formset_factory, modelformset_factory, HiddenInput
from django.forms.models import model_to_dict
from django.contrib.auth.decorators import login_required
from django.urls import reverse

from userauth.models import MCUser, CustomUser
from userauth.decorators import doctor_required

from mc_data.models import ValuedMotivation, AdditionalPersonalData, Motivation,\
    ValuedContraindication, Contraindication, Exam, MCPeriod

from api.serializers import CustomUserSerializer

from consultation.forms import AdditionalPersonalDataForm, ValuedMotivationForm,\
    ValuedContraindicationForm, ValuedMotivationFormSet, \
    ValuedContraindicationFormSet

import consultation.forms as cforms

def index(request):
    return redirect('/fr/consultation/pick')


@doctor_required
def pick(request):
    return render(request, 'consultation/pick.html')


@doctor_required
def start(request, pk_mcuser_as_user):
    try:
        user = CustomUser.objects.get(pk=pk_mcuser_as_user)
    except CustomUser.DoesNotExist:
        return HttpResponse('Non-existing user.')

    user_serializer = CustomUserSerializer(user)

    mcuser = user.as_mc_user

    formset_list = ['motivation','contraindication']


    VmotivationsFormset = formset_factory(ValuedMotivationForm,
                                          formset=ValuedMotivationFormSet,
                                          extra=5,
                                          can_delete=True)
    VContraindicationFormset = formset_factory(
        ValuedContraindicationForm,
        formset=ValuedContraindicationFormSet,
        extra=5,
        can_delete=True
    )

    all_additional_personal_data = AdditionalPersonalData.objects.filter(mc_user=mcuser)
    if all_additional_personal_data.exists():
        additional_personal_data = all_additional_personal_data.last()
    else:
        additional_personal_data = AdditionalPersonalData(mc_user=mcuser)
        additional_personal_data.save()

    init_values_motiv = [model_to_dict(m) \
                         for m in additional_personal_data.motivations.all()]

    init_values_contra = [model_to_dict(c) \
                          for c in additional_personal_data.contraindications.all()]

    vmotivations_form = VmotivationsFormset(
        initial=init_values_motiv,
        prefix=formset_list[0], #get mcuser ones of last init meeting
    )
    vcontraindications_form = VContraindicationFormset(
        initial=init_values_contra,
        prefix=formset_list[1], #get mcuser ones of last init meeting
    )

    additional_personal_data_form = AdditionalPersonalDataForm(instance=additional_personal_data,
                                                               prefix='pers_data')

    formset_list = [{'prefix': prefix, 'url_post': ''}\
                    for prefix in formset_list]

    exams = []

    for SExam in Exam.__subclasses__():
        exam = {}
        exam['prefix'] = SExam.__name__
        exam['title'] = SExam._meta.verbose_name.title()
        exam['form_set'] = modelformset_factory(
            SExam, #getattr(cforms, f'{SExam.__name__}Form'),
            extra=5,
            can_delete=True,
            fields=SExam.get_ordered_fields(),
            exclude=('registered_by', 'registered_at'),
            widgets={'mc_user': HiddenInput()}
        )(
                queryset=SExam.objects.filter(mc_user=mcuser),
                prefix=exam['prefix'])

        # prefill mc_user and prescriber fields
        for f in exam['form_set']:
            f['mc_user'].initial = mcuser
            if f['prescriber'].initial is None:
                f['prescriber'].initial = request.user.as_doctor

        exams.append(exam)
        formset_list.append({'prefix': exam['prefix'],
                             'url_post': reverse('consultation:save_exam')})
        
    periods = []
    for Period in MCPeriod.__subclasses__():
        period = {}
        period['prefix'] = Period.__name__
        period['title'] = Period._meta.verbose_name#.title()
        period['form_set'] = modelformset_factory(
            Period,
            extra=5,
            can_delete=True,
            fields=Period.get_ordered_fields(),
            exclude = ('registered_by', 'registered_at'),
            widgets = {'mc_user': HiddenInput()}
        )(
                queryset=Period.objects.filter(mc_user=mcuser),
                prefix=period['prefix'])

        # prefill mc_user fields
        for f in period['form_set']:
            f['mc_user'].initial = mcuser

        periods.append(period)
        formset_list.append({'prefix': period['prefix'],
                             'url_post': reverse('consultation:save_period')})

    return render(request, 'consultation/start.html',
                  {'mcuser': mcuser,
                   'user_pk': pk_mcuser_as_user,
                   'user': request.user,
                   'formset_list': formset_list,
                   'additional_personal_data_form': additional_personal_data_form,
                   'vmotivations_form': vmotivations_form,
                   'vcontraindications_form': vcontraindications_form,
                   'user_serializer': user_serializer,
                   'exams': exams,
                   'periods': periods})


def save_additional_personal_data(req, pk_mcuser):
    if req.method != 'POST' or not req.is_ajax():
        return HttpResponse(status=status.HTTP_406_NOT_ACCEPTABLE)

    try:
        mcuser = MCUser.objects.get(pk=pk_mcuser)
    except MCUser.DoesNotExist:
        return HttpResponse('Non-existing MC user.')

    
    formset_list = ['motivation','contraindication']

    additional_personal_data_form = AdditionalPersonalDataForm(req.POST,
                                                               prefix='pers_data')

    VmotivationsFormset = formset_factory(ValuedMotivationForm,
                                          formset=ValuedMotivationFormSet,
                                          extra=5,
                                          can_delete=True)

    vmotivations_form = VmotivationsFormset(req.POST,
                                            prefix=formset_list[0])
    
    VcontraindicationsFormset = formset_factory(
        ValuedContraindicationForm,
        formset=ValuedContraindicationFormSet,
        extra=5,
        can_delete=True
    )

    vcontraindications_form = VcontraindicationsFormset(req.POST,
                                                prefix=formset_list[1])

    additional_personal_data = additional_personal_data_form.save(commit=False)
    additional_personal_data.mc_user = mcuser
    additional_personal_data.registered_by = req.user
    additional_personal_data.save()

    if vmotivations_form.is_valid():
        vmotivations_form.save(additional_personal_data.motivations)
    if vcontraindications_form.is_valid():
        vcontraindications_form.save(additional_personal_data.contraindications)

    return HttpResponse(status=status.HTTP_200_OK)


def save_exam(request):
    if request.method != 'POST' or not request.is_ajax():
        return HttpResponse(status=status.HTTP_406_NOT_ACCEPTABLE)

    for SExam in Exam.__subclasses__():
        prefix = SExam.__name__
        if not next(iter(request.POST.keys())).startswith(prefix):
            continue
        exam_form_set = modelformset_factory(
            SExam,
            fields=SExam.get_ordered_fields(),
            exclude = ('registered_by', 'registered_at'),
            can_delete=True)(request.POST,
                             prefix=prefix)
        if exam_form_set.is_valid():
            for cd in exam_form_set.cleaned_data:
                cd['registered_by'] = request.user.as_doctor
            exam_form_set.save()
        else:
            print(exam_form_set.errors)
            
    return HttpResponse(status=status.HTTP_200_OK)


def save_period(request):
    if request.method != 'POST' or not request.is_ajax():
        return HttpResponse(status=status.HTTP_406_NOT_ACCEPTABLE)

    for Period in MCPeriod.__subclasses__():
        prefix = Period.__name__
        if not next(iter(request.POST.keys())).startswith(prefix):
            continue
        period_form_set = modelformset_factory(
            Period,
            fields=Period.get_ordered_fields(),
            exclude = ('registered_by', 'registered_at'),
            can_delete=True)(request.POST,
                             prefix=prefix)
        if period_form_set.is_valid():
            for cd in period_form_set.cleaned_data:
                cd['registered_by'] = request.user.as_doctor
            period_form_set.save()
        else:
            print(period_form_set.errors)
            
    return HttpResponse(status=status.HTTP_200_OK)

consultation/templates/consultation/base.html
{% load static %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}

<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE }}">

  <head>
    <style>
    </style>
    {% block css %}
    {% endblock %}
      <script src="{% url 'javascript-catalog' %}"></script>

    {% block jquery %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script>
        let _ = gettext ;
    </script>
    {% endblock %}
  </head>
  

  <body>
    <nav>
      <ul>
        <li style="float:right">
          <a href="{% url 'account_logout' %}">{% trans "Sign out" %}</a>
        </li>
        <li style="float:right">
          {% if user.is_authenticated %}
          {% trans 'Signed in as ' %} {{ user.username }}
          {% endif %}
        </li>
      </ul>
    </nav>

    <section id="content">
      {% block content %}{% endblock %}
    </section>

    {% block javascript %}
    {% endblock %}
    
  </body>
</html>

consultation/templates/consultation/pick.html
{% extends 'consultation/base.html' %}

{% load static %}
{% load i18n %}

{% block css %}
<link rel="stylesheet" href="{% static 'consultation/base.css' %}" />
{% endblock %}


{% block content %}
<script>
  let url_approx_search = "{% url 'api:mcuser-list' %}" ;
  let url_start = "{% url 'consultation:start' 0 %}" ;
  url_start = url_start.slice(0,-1) ;
</script>
<div>
  {% trans "Find a patient" %} ({% trans "by last name excerpt" %}):
  <input id="search-field" type="text" value=""><button id="search-button">{% trans 'Search' %}</button>
  <table class='hp-table'>
    <thead style="visibility: hidden" id="table-head">
      <tr>
        <td>{% trans 'First name' %}</td> <td>{% trans 'Last name' %}</td> <td>{% trans 'Date of birth' %}</td>
      </tr>
    </thead>
    <tbody id="table-body">
    </tbody>
  </table>
</div>
{% endblock %}

{% block javascript %}
<script src="{% static 'consultation/search.js' %}"></script>
{% endblock %}

consultation/templates/consultation/start.html
{% extends 'consultation/base.html' %}
{% load crispy_forms_tags %}
{% load rest_framework %}
{% load static %}
{% load i18n %}


{% block css %}
<link rel="stylesheet" href="{% static 'consultation/tabs.css' %}" />
{% endblock %}

{% block content %}
{% csrf_token %}
<script>
  const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;
  let formset_list = {{ formset_list | safe}} ;

  let url_update_user = "{% url 'api:mcuser-detail' user_pk %}" ;
  let url_save_additional_personal_data = "{% url 'consultation:save_additional_personal_data' mcuser.pk %}";
</script>

    <h1> {% trans 'Consultation for' %} {{ mcuser.user.first_name }} {{ mcuser.user.last_name }} </h1>

    <div class="container">
    <div class="tab">
  <button class="tab-link" onclick="open_tab(event, 'generic')">{% trans 'Generic' %}</button>
  <button class="tab-link" onclick="open_tab(event, 'further')">{% trans 'Complementary' %}</button>
  <button class="tab-link" onclick="open_tab(event, 'clinical')">{% trans 'Medical exams' %}</button>
  <button class="tab-link" onclick="open_tab(event, 'periods')">{% trans 'Periods' %}</button>
  <button class="tab-link" onclick="open_tab(event, 'trajectory')">{% trans 'Trajectory' %}</button>
</div>

<div id='generic' class='tab-content'>
  <h3>{% trans 'Generic' %}</h3>
  <h4>{% trans 'Patient' %}</h4>
  <form id="ser_user" onsubmit="return false">
    {% csrf_token %}
    {% render_form user_serializer %}
    <button id='btn_ser_user'>{% trans 'Save' %}</button>
    <div id='error-list' style='color:brown'>  </div>
  </form>
</div>

<div id='further' class='tab-content'>
  <h3>{% trans 'Additional information' %} </h3>
  <div>
  <h4></h4>
  <form id='personal_data_form'>
    {{ additional_personal_data_form | crispy}}
  </form>
  <h4>{% trans 'Motivations' %}</h4>
  <form id='{{formset_list.0.prefix}}' onsubmit="return false">
    {{ vmotivations_form | crispy }}
    <button id='btn_more_{{formset_list.0.prefix}}'>{% trans 'Add a motivation' %}</button>
  </form>
  <h4>{% trans 'Contraindications' %}</h4>
  <form id='{{formset_list.1.prefix}}' onsubmit="return false">
    {{ vcontraindications_form | crispy }}
    <button id='btn_more_{{formset_list.1.prefix}}'>{% trans 'Add a contraindication' %}</button>
  </form>
  <br/><br/><br/>
  <button id='btn_comp_save'>{% trans 'Save' %}</button>
  </div>
</div>
<div id='clinical' class='tab-content'>
  <h3>{% trans 'Medical exams' %}</h3>
  {% for exam  in exams %}
  <h4> {{exam.title}} </h4>
  <form id='{{exam.prefix}}' onsubmit="return false">
    {{ exam.form_set | crispy }}
    <button id='btn_more_{{exam.prefix}}'>{%  trans "Add a " %} {{exam.title | lower}} </button>
    <button id='btn_save_{{exam.prefix}}'>{% trans "Save" %}</button>
  </form>
  {% endfor %}
</div>
<div id='periods' class='tab-content'>
  <h3>{% trans 'Periods' %}</h3>
  {% for period  in periods %}
  <h4> {{period.title}} </h4>
  <form id='{{period.prefix}}' onsubmit="return false">
    {{ period.form_set | crispy }}
    <button id='btn_more_{{period.prefix}}'>{%  trans "Add a " %} {{period.title | lower}}</button>
    <button id='btn_save_{{period.prefix}}'>{% trans "Save" %}</button>
  </form>
  {% endfor %}
</div>
<div id='trajectory' class='tab-content'>
  <h3>{% trans 'Trajectory' %}</h3>
</div>
</div>






{% endblock %}

{% block javascript %}
<script src="{% static 'consultation/search.js' %}"></script>
<script src="{% static 'consultation/tabs.js' %}"></script>
<script src="{% static 'consultation/user_form.js' %}"></script>
<script src="{% static 'consultation/formsets-show-hide.js' %}"></script>
<script src="{% static 'consultation/save.js' %}"></script>
{% endblock %}