api/urls.py
from django.urls import path
from django.conf.urls import include

from rest_framework import routers, permissions

from api.views import MCUserViewSet

app_name = 'api'

routerUser = routers.SimpleRouter()

routerUser.register('mcuser', MCUserViewSet, basename='mcuser')

urlpatterns = [
    path('user/', include(routerUser.urls)),
]

consultation/urls.py
from django.urls import path

from consultation.views import pick, start, save_additional_personal_data, save_exam,\
    save_period

app_name = 'consultation'

urlpatterns = [
    path('pick', pick, name='pick'),
    path('start/<int:pk_mcuser_as_user>', start, name='start'),
    path('save_additional_personal_data/<int:pk_mcuser>',
         save_additional_personal_data,
         name='save_additional_personal_data'),
    path('save_exam', save_exam, name='save_exam'),
    path('save_period', save_period, name='save_period'),
]

userauth/urls.py
from django.urls import path
from .views import profile_view, CustomUserUpdateView, CustomUserDeleteView

urlpatterns = [
    path('profile/', profile_view, name='account_profile'),
    path('<int:pk>/update/', CustomUserUpdateView.as_view(template_name='account/update.html'), name='account_update'),
    path('<int:pk>/delete/', CustomUserDeleteView.as_view(template_name='account/delete.html'), name='account_delete'),
]

userauth/models.py
from django.contrib.auth.models import AbstractUser
from django.core.validators import RegexValidator
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from faker import Faker

from django_countries.fields import CountryField


class CustomUser(AbstractUser):
    display_name = models.CharField(verbose_name=_("Display name"), max_length=30,
                                    help_text=_("Will be shown e.g. when commenting"))
    date_of_birth = models.DateField(verbose_name=_("Date of birth"), blank=True, null=True)
    address1 = models.CharField(verbose_name=_("Address line 1"), max_length=1024, blank=True, null=True)
    address2 = models.CharField(verbose_name=_("Address line 2"), max_length=1024, blank=True, null=True)
    zip_code = models.CharField(verbose_name=_("Postal Code"), max_length=12, blank=True, null=True)
    city = models.CharField(verbose_name=_("City"), max_length=1024, blank=True, null=True)
    country = CountryField(blank=True, null=True)
    phone_regex = RegexValidator(regex=r"^\+(?:[0-9]●?){6,14}[0-9]$",
                                 message=_("Enter a valid international mobile phone number "
                                           "starting with +(country code)"))
    mobile_phone = models.CharField(validators=[phone_regex], verbose_name=_("Mobile phone"), max_length=17, blank=True,
                                    null=True)
    ine_regex = RegexValidator(regex=r'^'
                                     '[12]'
                                     '[0-9]{2}'
                                     '(0[1-9]|1[0-2])'
                                     '(2[AB]|[0-9]{2})'
                                     '[0-9]{6}'
                                     '[0-9]{2}'
                                     '$',
                               message=_("Enter a valid INE number"))
    ine_number = models.CharField(validators=[ine_regex], verbose_name=_("INE number"),
                                  max_length=15, blank=True, null=True)
    additional_information = models.CharField(verbose_name=_("Additional information"), max_length=4096, blank=True,
                                              null=True)
    photo = models.ImageField(verbose_name=_("Photo"), upload_to='photos/', default='photos/default-user-avatar.png')

    roles = models.ManyToManyField('Role', related_name='users')

    class Meta:
        ordering = ['last_name']
        verbose_name = _('Custom user')

    def get_absolute_url(self):
        return reverse('account_profile')

    def __str__(self):
        return f"{self.username}"


class Role(models.Model):
    """
    The Role entries are managed by the system,
    automatically created via a Django data migration.
    """
    MC_USER = 1
    DOCTOR = 2
    ACTIVIST = 3
    WEB_ADMIN = 4
    JOURNALIST = 5
    ROLE_CHOICES = (
        (MC_USER, _('Male contraception user')),
        (DOCTOR, _('Doctor')),
        (ACTIVIST, _('Activist')),
        (WEB_ADMIN, _('Web administrator')),
        (JOURNALIST, _('Journalist')),
    )

    id = models.PositiveSmallIntegerField(choices=ROLE_CHOICES, primary_key=True)

    def __str__(self):
        return self.get_id_display()


class MCUser(models.Model):
    user = models.OneToOneField('CustomUser', on_delete=models.CASCADE, related_name='as_mc_user')
    fake_first_name = models.CharField(max_length=20, null=True)
    fake_last_name = models.CharField(max_length=20, null=True)

    def __str__(self):
        return f"{self.user.username}"

    class Meta:
        verbose_name = _('Male contraception user')

    def save(self, *args, **kwargs):
        if not self.pk:
            faker = Faker(['fr_FR', 'it_IT'])
            self.fake_first_name = faker.first_name_male()
            self.fake_last_name = faker.last_name()
        super(MCUser, self).save(*args, **kwargs)


class Partner(models.Model):
    user = models.OneToOneField('CustomUser', on_delete=models.CASCADE, related_name='as_partner')
    mc_user = models.ForeignKey('CustomUser', on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.user.username}"

    class Meta:
        verbose_name = _('Partner')


class Doctor(models.Model):
    user = models.OneToOneField('CustomUser', on_delete=models.CASCADE, related_name='as_doctor')

    def __str__(self):
        return f"{self.user.username}"

    class Meta:
        verbose_name = _('Doctor')


class Activist(models.Model):
    user = models.OneToOneField('CustomUser', on_delete=models.CASCADE, related_name='as_activist')
    organizations = models.ManyToManyField('Organization', through='ActivistSettings')

    def __str__(self):
        return f"{self.user.username} - {self.organizations.all()}"

    class Meta:
        verbose_name = _('Activist')


class ActivistSettings(models.Model):
    """
    This model allows to add additionnal settings to the
    relation between Activist and Organization
    """
    activist = models.ForeignKey('Activist', on_delete=models.CASCADE)
    organization = models.ForeignKey('Organization', on_delete=models.CASCADE)
    is_main = models.BooleanField(default=False)
    leader = models.BooleanField(default=False)

    def __str__(self):
        return (f'U:{self.activist.user.username}, O:{self.organization.name}, '
                f'{"leader" if self.leader else "activist"}')

    class Meta:
        verbose_name = _('Activist settings')


class Organization(models.Model):
    name = models.CharField(verbose_name=_("Name"), max_length=256)
    abbreviation = models.CharField(verbose_name=_("Abbreviation"), max_length=8)

    class Meta:
        verbose_name = _('Organization')

userauth/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
from .models import CustomUser

from wagtail.users.forms import UserCreationForm, UserEditForm


class WagtailUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = CustomUser
        widgets = {'date_of_birth': forms.DateInput(attrs={'type':'date'})}


class WagtailUserEditForm(UserEditForm):
    class Meta(UserEditForm.Meta):
        model = CustomUser
        widgets = {'date_of_birth': forms.DateInput(attrs={'type':'date'})}


class SignupForm(forms.Form):
    first_name = forms.CharField(max_length=30, label=_("First name"))
    last_name = forms.CharField(max_length=30, label=_("Last name"))
    display_name = forms.CharField(max_length=30, label=_("Display name"), help_text=_("Will be shown e.g. when commenting"))

    def signup(self, request, user):
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.display_name = self.cleaned_data['display_name']
        user.save()


class CustomUserUpdateForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ['first_name', 'last_name', 'display_name', 'date_of_birth', 'ine_number', 'address1', 'address2', 'zip_code', 'city', 'country', 'mobile_phone', 'additional_information', 'photo',]
        widgets = {'date_of_birth': forms.DateInput(attrs={'type':'date'})}

userauth/views.py
from .forms import CustomUserUpdateForm
from .models import CustomUser
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic.edit import UpdateView, DeleteView

# Create your views here.
@login_required
def profile_view(request):
    return render(request, 'account/profile.html')


class CustomUserUpdateView(UpdateView):
    model = CustomUser
    form_class = CustomUserUpdateForm


class CustomUserDeleteView(DeleteView):
    model = CustomUser
    success_url = reverse_lazy('account_signup')

userauth/templates/userauth/account/base_card.html
{% extends 'base.html' %}

{% block content %}

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-8 col-md-10 col-sm-12">
                <div class="card">
                    <div class="card-header">
                        {% block card-header %}{% endblock %}
                    </div>
                    <div class="card-body">
                        {% block card-body %}{% endblock %}
                    </div>
                    <div class="card-footer text-muted text-center">
                        {% block card-footer %}{% endblock %}
                    </div>
               </div>
            </div>
        </div>
    </div>

{% endblock %}

userauth/templates/userauth/account/delete.html
{% extends 'account/base_card.html' %}

{% load i18n %}

{% block title %}{% trans "Delete account" %}{% endblock %}

{% block card-header %}
    <h3>{% trans "Delete account" %}</h3>
{% endblock %}

{% block card-body %}

    <form method="POST">
        {% csrf_token %}
        <p>{% trans "Are you sure you want to delete the account" %} {{ object.email }}?</p>
        <button type="submit" class="btn btn-danger">{% trans "Delete" %}</button>
    </form>
    <br><p>{% trans "No, keep my account" %}</p>
    <a href="/" class="btn btn-outline-primary">{% trans "Return to site" %}</a>

{% endblock %}

userauth/templates/userauth/account/email_confirm.html
{% extends 'account/base_card.html' %}

{% load i18n account %}

{% block title %}{% trans "Confirm e-mail address" %}{% endblock %}

{% block card-header %}
    <h3>{% trans "Confirm e-mail address" %}</h3>
{% endblock %}

{% block card-body %}

    {% if confirmation %}

        {% user_display confirmation.email_address.user as user_display %}

        <p>{% blocktrans with confirmation.email_address.email as email %}Please confirm that <a href="mailto:{{ email }}">{{ email }}</a> is an e-mail address for user {{ user_display }}.{% endblocktrans %}</p>

        <form method="post" action="{% url 'account_confirm_email' confirmation.key %}">
            {% csrf_token %}
            <button type="submit">{% trans "Confirm" %}</button>
        </form>

    {% else %}

        {% url 'account_email' as email_url %}

        <p>{% blocktrans %}This e-mail confirmation link expired or is invalid. Please <a href="{{ email_url }}">issue a new e-mail confirmation request</a>.{% endblocktrans %}</p>

    {% endif %}

{% endblock %}

userauth/templates/userauth/account/form_field.html
{% load widget_tweaks %}

<small>{{ field.label_tag }}</small>

{% if form.is_bound %}
    {% if field.errors or form.non_field_errors %}
        {% render_field field class="form-control is-invalid" %}
        <div class="invalid-feedback">
            {{ form.non_field_errors }}
            {{ field.errors }}
        </div>
    {% else %}
        {% render_field field class="form-control is-valid" %}
    {% endif %}
{% else %}
    {% with "form-control input-field-"|add:field.name as field_class %}{% render_field field class=field_class %}{% endwith %}
{% endif %}

userauth/templates/userauth/account/login.html
{% extends 'account/base_card.html' %}

{% load i18n socialaccount %}

{% block title %}{% trans "Sign in" %}{% endblock %}

{% block card-header %}
    <h3>{% trans "Sign in" %}</h3>
{% endblock %}

{% block card-body %}

    {% get_providers as socialaccount_providers %}

    <form method="POST" action="{% url 'account_login' %}" class="needs-validation" novalidate>
        {% csrf_token %}
        <div class="form-group">
            {% with field=form.login %}{% include "account/form_field.html" %}{% endwith %}
        </div>
        <div class="form-group">
            {% with field=form.password %}{% include "account/form_field.html" %}{% endwith %}
        </div>
        <button type="submit" class="btn btn-outline-primary">{% trans "Sign in" %}</button>
    </form>
    {% if socialaccount_providers %}
        <br>
        <p>{% blocktrans with site.name as site_name %}or sign in with one of your existing third party accounts:{% endblocktrans %}</p>
        {% include "socialaccount/provider_list.html" with process="login" %}
    {% endif %}

{% endblock %}

{% block card-footer %}
    <p>{% trans "Don't have an account?" %} <a href="{{ signup_url }}">{% trans "Sign up" %}</a></p>
    <small>
        <a class="text-muted" href="{% url 'account_reset_password' %}">{% trans "Forgot password?" %}</a>
    </small>
{% endblock %}

userauth/templates/userauth/account/logout.html
{% extends 'account/base_card.html' %}

{% load i18n %}

{% block title %}{% trans "Sign out" %}{% endblock %}

{% block card-header %}
    <h3>{% trans "Sign out" %}</h3>
{% endblock %}

{% block card-body %}

    <p>{% trans "Are you sure you want to sign out?" %}</p>

    <form method="POST" action="{% url 'account_logout' %}">
        {% csrf_token %}
        <button type="submit" class="btn btn-outline-primary btn-sm">{% trans "Sign out" %}</button>
    </form>

    <br><p>{% trans "No, stay logged in" %}</p>
    <a href="/" class="btn btn-outline-primary">{% trans "Return to site" %}</a>

{% endblock %}

userauth/templates/userauth/account/password_reset.html
{% extends 'account/base_card.html' %}

{% load i18n %}

{% block title %}{% trans "Password reset" %}{% endblock %}

{% block card-header %}
    <h3>{% trans "Password reset" %}</h3>
{% endblock %}

{% block card-body %}

    <form method="POST" action="{% url 'account_reset_password' %}" class="needs-validation" novalidate>
        {% csrf_token %}
        <div class="form-group">
            {% with field=form.email %}{% include "account/form_field.html" %}{% endwith %}
        </div>
        <button type="submit" class="btn btn-outline-secondary">{% trans "Reset password" %}</button>
    </form>

{% endblock %}

userauth/templates/userauth/account/password_reset_done.html
{% extends 'account/base_card.html' %}

{% load i18n %}

{% block title %}{% trans "Password reset" %}{% endblock %}

{% block card-header %}
    <h3>{% trans "Password reset" %}</h3>
{% endblock %}

{% block card-body %}

    <p>{% trans "We have sent you an e-mail. Please contact us if you do not receive it within a few minutes." %}</p>

{% endblock %}

userauth/templates/userauth/account/password_reset_from_key.html
{% extends "account/base_card.html" %}

{% load i18n %}

{% block title %}{% trans "Change password" %}{% endblock %}

{% block card_header %}
    <h3>{% if token_fail %}{% trans "Bad token" %}{% else %}{% trans "Change password" %}{% endif %}</h3>
{% endblock %}

{% block card-body %}
    {% if token_fail %}
        {% url 'account_reset_password' as passwd_reset_url %}
        <p>{% blocktrans %}The password reset link was invalid, possibly because it has already been used.  Please request a <a href="{{ passwd_reset_url }}">new password reset</a>.{% endblocktrans %}</p>
    {% else %}
        {% if form %}
            <form method="POST" action="{{ action_url }}" class="needs-validation" novalidate>
                {% csrf_token %}
                <div class="form-group">
                    {% with field=form.password1 %}{% include "account/form_field.html" %}{% endwith %}
                </div>
                <div class="form-group">
                    {% with field=form.password2 %}{% include "account/form_field.html" %}{% endwith %}
                </div>
                <input type="submit" name="action" class="btn btn-outline-secondary" value="{% trans "Change password" %}"/>
            </form>
        {% else %}
            <p>{% trans "Your password is now changed." %}</p>
        {% endif %}
    {% endif %}
{% endblock %}

userauth/templates/userauth/account/password_reset_from_key_done.html
{% extends "account/base_card.html" %}

{% load i18n %}
{% block title %}{% trans "Change password" %}{% endblock %}

{% block card-header %}
    <h3>{% trans "Change password" %}</h3>
{% endblock %}

{% block card-body %}
    <p>{% trans "Your password is now changed." %}</p>
{% endblock %}

userauth/templates/userauth/account/profile.html
{% extends 'account/base_card.html' %}

{% load i18n %}

{% block title %}{% trans "Profile" %}{% endblock %}

{% block card-header %}
    <h3>{% trans "Account profile" %}</h3>
{% endblock %}

{% block card-body %}

    <div class="container">
        <div class="row">
            <div class="col border">
                <small>{% trans "E-mail" %}:</small><br>
                {{ request.user.email }}
            </div>
            <div class="col border">
                <small>{% trans "Display name" %}:</small><br>
                {{ request.user.display_name }}
            </div>
        </div>
        <div class="row">
            <div class="col border">
                <small>{% trans "First name" %}:</small><br>
                {{ request.user.first_name|default:'' }}
            </div>
            <div class="col border">
                <small>{% trans "Last name" %}:</small><br>
                {{ request.user.last_name|default:'' }}
            </div>
        </div>
        <div class="row">
            <div class="col border">
                <small>{% trans "INE number" %}:</small><br>
                {{ request.user.ine_number|default:'' }}
            </div>
        </div>
        <div class="row">
            <div class="col border">
                <small>{% trans "Address1" %}:</small><br>
                {{ request.user.address1|default:'' }}
            </div>
        </div>
        <div class="row">
            <div class="col border">
                <small>{% trans "Address2" %}:</small><br>
                {{ request.user.address2|default:'' }}
            </div>
        </div>
        <div class="row">
            <div class="col border">
                <small>{% trans "City" %}:</small><br>
                {{ request.user.city|default:'' }}
            </div>
            <div class="col-2 border">
                <small>{% trans "Postal code" %}:</small><br>
                {{ request.user.zip_code|default:'' }}
            </div>
            <div class="col-4 border">
                <small>{% trans "Country" %}:</small><br>
                {{ request.user.country|default:'' }}
            </div>
        </div>
        <div class="row">
            <div class="col border">
                <small>{% trans "Mobile phone" %}:</small><br>
                {{ request.user.mobile_phone|default:'' }}
            </div>
            <div class="col border">
                <small>{% trans "Date of birth" %}:</small><br>
                {{ request.user.date_of_birth|default:'' }}
            </div>
        </div>
        <div class="row">
            <div class="col border">
                <small>{% trans "Additional information" %}:</small><br>
                {{ request.user.additional_information|default:'' }}
            </div>
        </div>
        <div class="row">
            <div class="col border">
                <small>{% trans "Photo" %}:</small><br>
                <img src="{{ request.user.photo.url }}" class="profile-image" alt="{% trans 'User photo' %}">
            </div>
        </div>
    </div>

{% endblock %}

{% block card-footer %}
    <div class="row">
        <div class="col border">
            <a href="{% url 'account_update' request.user.pk %}">{% trans "Update your account" %}</a>
        </div>
         <div class="col border">
            <a href="{% url 'consultation:pick' %}">{% trans "Input data" %}</a>
        </div>
    </div>

{% endblock %}

userauth/templates/userauth/account/signup.html
{% extends 'account/base_card.html' %}

{% load i18n socialaccount %}

{% block title %}{% trans "Sign up" %}{% endblock %}

{% block card-header %}
    <h3>{% trans "Sign up" %}</h3>
{% endblock %}

{% block card-body %}

    {% get_providers as socialaccount_providers %}

    <form method="POST" action="{% url 'account_signup' %}" class="needs-validation" novalidate>
        {% csrf_token %}
        <div class="form-row">
            <div class="form-group col-md-6">
                {% with field=form.email %}{% include "account/form_field.html" %}{% endwith %}
            </div>
            <div class="form-group col-md-6">
                {% with field=form.display_name %}{% include "account/form_field.html" %}{% endwith %}
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-6">
                {% with field=form.password1 %}{% include "account/form_field.html" %}{% endwith %}
            </div>
            <div class="form-group col-md-6">
                {% with field=form.password2 %}{% include "account/form_field.html" %}{% endwith %}
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-6">
                {% with field=form.first_name %}{% include "account/form_field.html" %}{% endwith %}
            </div>
            <div class="form-group col-md-6">
                {% with field=form.last_name %}{% include "account/form_field.html" %}{% endwith %}
            </div>
        </div>
        <button type="submit" class="btn btn-outline-primary">{% trans "Sign up" %}</button>
    </form>
    {% if socialaccount_providers %}
        <br>
        <p>{% blocktrans with site.name as site_name %}or sign up with one of your existing third party accounts:{% endblocktrans %}</p>
        {% include "socialaccount/provider_list.html" with process="login" %}
    {% endif %}

{% endblock %}

{% block card-footer %}
    <p>{% trans "Already have an account?" %} <a href="{% url 'account_login' %}">{% trans "Sign in" %}</a></p>
{% endblock %}

userauth/templates/userauth/account/update.html
{% extends 'account/base_card.html' %}

{% load i18n socialaccount %}

{% block title %}{% trans "Update account" %}{% endblock %}

{% block card-header %}
    <h3>{% trans "Update account" %}</h3>
{% endblock %}

{% block card-body %}

    {% get_providers as socialaccount_providers %}

    <form method="POST" action="{% url 'account_update' request.user.pk %}" enctype="multipart/form-data" class="needs-validation" novalidate>
        {% csrf_token %}
        <div class="form-group">
            {% with field=form.display_name %}{% include "account/form_field.html" %}{% endwith %}
        </div>
        <div class="form-row">
            <div class="form-group col-md-6">
                {% with field=form.first_name %}{% include "account/form_field.html" %}{% endwith %}
            </div>
            <div class="form-group col-md-6">
                {% with field=form.last_name %}{% include "account/form_field.html" %}{% endwith %}
            </div>
        </div>
        <div class="form-group">
            {% with field=form.address1 %}{% include "account/form_field.html" %}{% endwith %}
        </div>
        <div class="form-group">
            {% with field=form.address2 %}{% include "account/form_field.html" %}{% endwith %}
        </div>
        <div class="form-row">
            <div class="form-group col-md-6">
                {% with field=form.city %}{% include "account/form_field.html" %}{% endwith %}
            </div>
            <div class="form-group col-md-2">
                {% with field=form.zip_code %}{% include "account/form_field.html" %}{% endwith %}
            </div>
            <div class="form-group col-md-4">
                {% with field=form.country %}{% include "account/form_field.html" %}{% endwith %}
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-6">
                {% with field=form.mobile_phone %}{% include "account/form_field.html" %}{% endwith %}
            </div>
            <div class="form-group col-md-6">
                {% with field=form.date_of_birth %}{% include "account/form_field.html" %}{% endwith %}
            </div>
        </div>
        <div class="form-group">
            {% with field=form.ine_number %}{% include "account/form_field.html" %}{% endwith %}
        </div>
        <div class="form-group">
            {% with field=form.additional_information %}{% include "account/form_field.html" %}{% endwith %}
        </div>
        <div class="form-group">
            {% with field=form.photo %}{% include "account/form_field.html" %}{% endwith %}
        </div>
        <button type="submit" class="btn btn-outline-primary">{% trans "Update" %}</button>
    </form>
    <br>
    {% if socialaccount_providers %}
        <br>
        <p>{% blocktrans with site.name as site_name %}Connect your existing account to one of your social accounts:{% endblocktrans %}</p>
        {% include "socialaccount/provider_list.html" with process="connect" %}
    {% endif %}
    <div class="text-center py-2">
        <small>
            <a href="{% url 'account_delete' request.user.pk %}" class="text-muted">{% trans "Delete your account" %}</a>
        </small>
    </div>

{% endblock %}

userauth/templates/userauth/account/verification_sent.html
{% extends 'account/base_card.html' %}

{% load i18n %}

{% block title %}{% trans "Verify your e-mail address" %}{% endblock %}

{% block card-header %}
    <h3>{% trans "Verify your e-mail address" %}</h3>
{% endblock %}

{% block card-body %}

    <p>{% blocktrans %}We have sent an e-mail to you for verification. Follow the link provided to finalize the signup process. Please contact us if you do not receive it within a few minutes.{% endblocktrans %}</p>

{% endblock %}